// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueOnion.PERSISTINCE.Context;

#nullable disable

namespace TrueOnion.PERSISTINCE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221226034521_myMigration")]
    partial class myMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "All",
                            InsertedDate = new DateTime(2021, 4, 1, 10, 9, 58, 908, DateTimeKind.Unspecified).AddTicks(124),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Computers",
                            InsertedDate = new DateTime(2021, 7, 1, 10, 58, 32, 671, DateTimeKind.Unspecified).AddTicks(9537),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Books",
                            InsertedDate = new DateTime(2022, 7, 17, 3, 17, 29, 143, DateTimeKind.Unspecified).AddTicks(8039),
                            ParentID = 2,
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Outdoors",
                            InsertedDate = new DateTime(2022, 4, 9, 14, 54, 55, 599, DateTimeKind.Unspecified).AddTicks(2540),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Outdoors",
                            InsertedDate = new DateTime(2022, 3, 20, 8, 20, 15, 206, DateTimeKind.Unspecified).AddTicks(2809),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Tools",
                            InsertedDate = new DateTime(2021, 10, 22, 3, 29, 8, 80, DateTimeKind.Unspecified).AddTicks(7743),
                            ParentID = 3,
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Grocery",
                            InsertedDate = new DateTime(2021, 10, 3, 5, 14, 20, 793, DateTimeKind.Unspecified).AddTicks(3498),
                            ParentID = 3,
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Music",
                            InsertedDate = new DateTime(2021, 7, 24, 18, 41, 4, 593, DateTimeKind.Unspecified).AddTicks(9238),
                            ParentID = 5,
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Industrial",
                            InsertedDate = new DateTime(2022, 9, 1, 17, 43, 45, 277, DateTimeKind.Unspecified).AddTicks(1989),
                            ParentID = 8,
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Baby",
                            InsertedDate = new DateTime(2021, 12, 13, 15, 5, 42, 985, DateTimeKind.Unspecified).AddTicks(5492),
                            ParentID = 9,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2022, 6, 9, 6, 57, 21, 661, DateTimeKind.Unspecified).AddTicks(6058),
                            Name = "Awesome Granite Pants",
                            Price = 52m,
                            Status = 1,
                            Stock = 95
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 1, 8, 23, 27, 42, 412, DateTimeKind.Unspecified).AddTicks(7792),
                            Name = "Awesome Frozen Pizza",
                            Price = 56m,
                            Status = 1,
                            Stock = 127
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2021, 11, 10, 21, 36, 8, 380, DateTimeKind.Unspecified).AddTicks(737),
                            Name = "Rustic Fresh Towels",
                            Price = 54m,
                            Status = 1,
                            Stock = 55
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 11, 3, 17, 5, 4, 170, DateTimeKind.Unspecified).AddTicks(2362),
                            Name = "Small Fresh Car",
                            Price = 50m,
                            Status = 1,
                            Stock = 131
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2022, 1, 10, 22, 33, 0, 0, DateTimeKind.Unspecified).AddTicks(1951),
                            Name = "Licensed Wooden Pants",
                            Price = 57m,
                            Status = 1,
                            Stock = 185
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2022, 6, 25, 0, 1, 48, 42, DateTimeKind.Unspecified).AddTicks(3269),
                            Name = "Licensed Metal Cheese",
                            Price = 51m,
                            Status = 1,
                            Stock = 189
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2022, 9, 19, 10, 3, 14, 746, DateTimeKind.Unspecified).AddTicks(5805),
                            Name = "Gorgeous Plastic Mouse",
                            Price = 56m,
                            Status = 1,
                            Stock = 147
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 4, 6, 23, 11, 46, 877, DateTimeKind.Unspecified).AddTicks(4760),
                            Name = "Intelligent Granite Cheese",
                            Price = 54m,
                            Status = 1,
                            Stock = 90
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 4, 3, 21, 20, 24, 782, DateTimeKind.Unspecified).AddTicks(5444),
                            Name = "Licensed Concrete Sausages",
                            Price = 57m,
                            Status = 1,
                            Stock = 59
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2021, 11, 16, 14, 18, 29, 816, DateTimeKind.Unspecified).AddTicks(8036),
                            Name = "Practical Concrete Bacon",
                            Price = 54m,
                            Status = 1,
                            Stock = 118
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2021, 10, 3, 1, 30, 41, 271, DateTimeKind.Unspecified).AddTicks(6241),
                            Name = "Fantastic Frozen Gloves",
                            Price = 55m,
                            Status = 1,
                            Stock = 125
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 6, 7, 20, 28, 18, 176, DateTimeKind.Unspecified).AddTicks(4143),
                            Name = "Awesome Frozen Shoes",
                            Price = 53m,
                            Status = 1,
                            Stock = 46
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2022, 3, 25, 18, 35, 38, 982, DateTimeKind.Unspecified).AddTicks(9699),
                            Name = "Incredible Rubber Towels",
                            Price = 57m,
                            Status = 1,
                            Stock = 168
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2021, 7, 16, 5, 59, 20, 722, DateTimeKind.Unspecified).AddTicks(9853),
                            Name = "Fantastic Fresh Fish",
                            Price = 54m,
                            Status = 1,
                            Stock = 161
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 9, 15, 8, 49, 41, 905, DateTimeKind.Unspecified).AddTicks(5938),
                            Name = "Ergonomic Cotton Towels",
                            Price = 50m,
                            Status = 1,
                            Stock = 15
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            InsertedDate = new DateTime(2022, 2, 21, 22, 57, 52, 907, DateTimeKind.Unspecified).AddTicks(2516),
                            Name = "Small Rubber Shirt",
                            Price = 49m,
                            Status = 1,
                            Stock = 76
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2022, 4, 3, 4, 35, 43, 481, DateTimeKind.Unspecified).AddTicks(639),
                            Name = "Tasty Fresh Towels",
                            Price = 52m,
                            Status = 1,
                            Stock = 168
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 10, 15, 4, 49, 55, 694, DateTimeKind.Unspecified).AddTicks(430),
                            Name = "Gorgeous Granite Bike",
                            Price = 54m,
                            Status = 1,
                            Stock = 144
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2021, 6, 20, 15, 21, 16, 287, DateTimeKind.Unspecified).AddTicks(657),
                            Name = "Ergonomic Steel Shoes",
                            Price = 57m,
                            Status = 1,
                            Stock = 46
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2021, 10, 27, 20, 55, 12, 750, DateTimeKind.Unspecified).AddTicks(8387),
                            Name = "Licensed Wooden Table",
                            Price = 53m,
                            Status = 1,
                            Stock = 126
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 4, 29, 20, 7, 10, 963, DateTimeKind.Unspecified).AddTicks(853),
                            Name = "Handmade Plastic Salad",
                            Price = 53m,
                            Status = 1,
                            Stock = 150
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 9, 1, 13, 38, 17, 722, DateTimeKind.Unspecified).AddTicks(3375),
                            Name = "Tasty Wooden Hat",
                            Price = 56m,
                            Status = 1,
                            Stock = 38
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2022, 10, 22, 4, 33, 30, 159, DateTimeKind.Unspecified).AddTicks(2818),
                            Name = "Refined Wooden Car",
                            Price = 55m,
                            Status = 1,
                            Stock = 159
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 8, 20, 11, 30, 34, 519, DateTimeKind.Unspecified).AddTicks(790),
                            Name = "Tasty Rubber Cheese",
                            Price = 51m,
                            Status = 1,
                            Stock = 131
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 6, 24, 4, 56, 52, 918, DateTimeKind.Unspecified).AddTicks(5810),
                            Name = "Awesome Steel Ball",
                            Price = 56m,
                            Status = 1,
                            Stock = 164
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2021, 11, 26, 12, 19, 0, 299, DateTimeKind.Unspecified).AddTicks(3424),
                            Name = "Generic Cotton Table",
                            Price = 56m,
                            Status = 1,
                            Stock = 144
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 1,
                            InsertedDate = new DateTime(2022, 3, 12, 11, 54, 18, 580, DateTimeKind.Unspecified).AddTicks(9543),
                            Name = "Gorgeous Cotton Pants",
                            Price = 53m,
                            Status = 1,
                            Stock = 169
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2021, 8, 7, 9, 8, 12, 945, DateTimeKind.Unspecified).AddTicks(7973),
                            Name = "Refined Soft Mouse",
                            Price = 51m,
                            Status = 1,
                            Stock = 141
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 1,
                            InsertedDate = new DateTime(2021, 8, 30, 2, 53, 25, 927, DateTimeKind.Unspecified).AddTicks(9711),
                            Name = "Fantastic Soft Pants",
                            Price = 50m,
                            Status = 1,
                            Stock = 153
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2021, 4, 25, 9, 54, 18, 683, DateTimeKind.Unspecified).AddTicks(4832),
                            Name = "Fantastic Fresh Keyboard",
                            Price = 52m,
                            Status = 1,
                            Stock = 117
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MadeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RealeseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductFeatures");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InsertedDate = new DateTime(2022, 8, 31, 21, 23, 52, 100, DateTimeKind.Unspecified).AddTicks(5817),
                            MadeIn = "Niger",
                            RealeseDate = new DateTime(2021, 4, 4, 4, 17, 2, 289, DateTimeKind.Unspecified).AddTicks(6553),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            InsertedDate = new DateTime(2022, 8, 22, 11, 48, 28, 682, DateTimeKind.Unspecified).AddTicks(5708),
                            MadeIn = "Netherlands Antilles",
                            RealeseDate = new DateTime(2021, 9, 16, 8, 13, 41, 619, DateTimeKind.Unspecified).AddTicks(5420),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            InsertedDate = new DateTime(2022, 6, 7, 11, 36, 28, 913, DateTimeKind.Unspecified).AddTicks(284),
                            MadeIn = "Oman",
                            RealeseDate = new DateTime(2022, 10, 26, 19, 25, 12, 387, DateTimeKind.Unspecified).AddTicks(3461),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            InsertedDate = new DateTime(2021, 9, 19, 21, 27, 33, 630, DateTimeKind.Unspecified).AddTicks(7832),
                            MadeIn = "Heard Island and McDonald Islands",
                            RealeseDate = new DateTime(2022, 11, 14, 19, 50, 18, 296, DateTimeKind.Unspecified).AddTicks(8549),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            InsertedDate = new DateTime(2022, 9, 27, 5, 52, 51, 812, DateTimeKind.Unspecified).AddTicks(3305),
                            MadeIn = "Fiji",
                            RealeseDate = new DateTime(2022, 2, 12, 4, 19, 40, 693, DateTimeKind.Unspecified).AddTicks(6130),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            InsertedDate = new DateTime(2022, 8, 30, 21, 21, 4, 514, DateTimeKind.Unspecified).AddTicks(9837),
                            MadeIn = "Kyrgyz Republic",
                            RealeseDate = new DateTime(2022, 1, 3, 19, 20, 30, 80, DateTimeKind.Unspecified).AddTicks(7380),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            InsertedDate = new DateTime(2022, 3, 4, 1, 20, 21, 834, DateTimeKind.Unspecified).AddTicks(7059),
                            MadeIn = "Sri Lanka",
                            RealeseDate = new DateTime(2022, 11, 5, 5, 45, 26, 405, DateTimeKind.Unspecified).AddTicks(8886),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            InsertedDate = new DateTime(2022, 8, 22, 15, 33, 17, 80, DateTimeKind.Unspecified).AddTicks(3529),
                            MadeIn = "Zimbabwe",
                            RealeseDate = new DateTime(2021, 7, 8, 14, 21, 17, 722, DateTimeKind.Unspecified).AddTicks(5454),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            InsertedDate = new DateTime(2021, 9, 10, 17, 28, 14, 399, DateTimeKind.Unspecified).AddTicks(7620),
                            MadeIn = "Kyrgyz Republic",
                            RealeseDate = new DateTime(2022, 3, 24, 10, 28, 11, 198, DateTimeKind.Unspecified).AddTicks(422),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            InsertedDate = new DateTime(2021, 6, 12, 6, 57, 43, 415, DateTimeKind.Unspecified).AddTicks(8114),
                            MadeIn = "Moldova",
                            RealeseDate = new DateTime(2022, 8, 21, 14, 26, 18, 792, DateTimeKind.Unspecified).AddTicks(5944),
                            Status = 1
                        },
                        new
                        {
                            ID = 11,
                            InsertedDate = new DateTime(2021, 7, 12, 14, 40, 40, 416, DateTimeKind.Unspecified).AddTicks(871),
                            MadeIn = "Nauru",
                            RealeseDate = new DateTime(2022, 6, 2, 9, 41, 34, 956, DateTimeKind.Unspecified).AddTicks(5132),
                            Status = 1
                        },
                        new
                        {
                            ID = 12,
                            InsertedDate = new DateTime(2021, 11, 29, 3, 2, 10, 955, DateTimeKind.Unspecified).AddTicks(881),
                            MadeIn = "Wallis and Futuna",
                            RealeseDate = new DateTime(2022, 12, 24, 5, 46, 9, 912, DateTimeKind.Unspecified).AddTicks(3630),
                            Status = 1
                        },
                        new
                        {
                            ID = 13,
                            InsertedDate = new DateTime(2022, 11, 5, 21, 10, 18, 287, DateTimeKind.Unspecified).AddTicks(2584),
                            MadeIn = "Canada",
                            RealeseDate = new DateTime(2021, 11, 30, 0, 38, 27, 40, DateTimeKind.Unspecified).AddTicks(4777),
                            Status = 1
                        },
                        new
                        {
                            ID = 14,
                            InsertedDate = new DateTime(2022, 2, 28, 0, 16, 14, 889, DateTimeKind.Unspecified).AddTicks(6210),
                            MadeIn = "Cayman Islands",
                            RealeseDate = new DateTime(2021, 6, 29, 8, 18, 53, 582, DateTimeKind.Unspecified).AddTicks(3074),
                            Status = 1
                        },
                        new
                        {
                            ID = 15,
                            InsertedDate = new DateTime(2022, 8, 1, 21, 4, 57, 871, DateTimeKind.Unspecified).AddTicks(9898),
                            MadeIn = "Turkmenistan",
                            RealeseDate = new DateTime(2022, 2, 22, 22, 20, 2, 630, DateTimeKind.Unspecified).AddTicks(4753),
                            Status = 1
                        },
                        new
                        {
                            ID = 16,
                            InsertedDate = new DateTime(2021, 4, 16, 18, 44, 4, 806, DateTimeKind.Unspecified).AddTicks(3589),
                            MadeIn = "Senegal",
                            RealeseDate = new DateTime(2022, 11, 18, 23, 37, 6, 389, DateTimeKind.Unspecified).AddTicks(6328),
                            Status = 1
                        },
                        new
                        {
                            ID = 17,
                            InsertedDate = new DateTime(2022, 3, 20, 4, 7, 41, 965, DateTimeKind.Unspecified).AddTicks(3757),
                            MadeIn = "Japan",
                            RealeseDate = new DateTime(2022, 1, 29, 6, 30, 3, 76, DateTimeKind.Unspecified).AddTicks(6911),
                            Status = 1
                        },
                        new
                        {
                            ID = 18,
                            InsertedDate = new DateTime(2021, 4, 21, 11, 18, 46, 762, DateTimeKind.Unspecified).AddTicks(9889),
                            MadeIn = "Hong Kong",
                            RealeseDate = new DateTime(2022, 1, 19, 12, 33, 6, 769, DateTimeKind.Unspecified).AddTicks(4724),
                            Status = 1
                        },
                        new
                        {
                            ID = 19,
                            InsertedDate = new DateTime(2022, 10, 20, 5, 48, 34, 355, DateTimeKind.Unspecified).AddTicks(3834),
                            MadeIn = "San Marino",
                            RealeseDate = new DateTime(2022, 6, 29, 15, 10, 17, 537, DateTimeKind.Unspecified).AddTicks(5009),
                            Status = 1
                        },
                        new
                        {
                            ID = 20,
                            InsertedDate = new DateTime(2021, 10, 16, 4, 7, 48, 453, DateTimeKind.Unspecified).AddTicks(123),
                            MadeIn = "Guadeloupe",
                            RealeseDate = new DateTime(2022, 5, 29, 2, 6, 58, 367, DateTimeKind.Unspecified).AddTicks(429),
                            Status = 1
                        },
                        new
                        {
                            ID = 21,
                            InsertedDate = new DateTime(2022, 2, 12, 14, 36, 51, 124, DateTimeKind.Unspecified).AddTicks(1134),
                            MadeIn = "Algeria",
                            RealeseDate = new DateTime(2021, 9, 28, 9, 29, 14, 814, DateTimeKind.Unspecified).AddTicks(304),
                            Status = 1
                        },
                        new
                        {
                            ID = 22,
                            InsertedDate = new DateTime(2022, 11, 10, 15, 48, 35, 286, DateTimeKind.Unspecified).AddTicks(6057),
                            MadeIn = "Oman",
                            RealeseDate = new DateTime(2022, 7, 28, 16, 52, 8, 742, DateTimeKind.Unspecified).AddTicks(949),
                            Status = 1
                        },
                        new
                        {
                            ID = 23,
                            InsertedDate = new DateTime(2022, 7, 21, 2, 8, 29, 51, DateTimeKind.Unspecified).AddTicks(211),
                            MadeIn = "Vanuatu",
                            RealeseDate = new DateTime(2022, 2, 14, 10, 56, 59, 925, DateTimeKind.Unspecified).AddTicks(9108),
                            Status = 1
                        },
                        new
                        {
                            ID = 24,
                            InsertedDate = new DateTime(2022, 8, 15, 17, 16, 53, 368, DateTimeKind.Unspecified).AddTicks(2585),
                            MadeIn = "Comoros",
                            RealeseDate = new DateTime(2021, 5, 14, 15, 6, 49, 640, DateTimeKind.Unspecified).AddTicks(3858),
                            Status = 1
                        },
                        new
                        {
                            ID = 25,
                            InsertedDate = new DateTime(2021, 12, 25, 4, 38, 23, 623, DateTimeKind.Unspecified).AddTicks(5665),
                            MadeIn = "Albania",
                            RealeseDate = new DateTime(2022, 3, 19, 13, 50, 51, 151, DateTimeKind.Unspecified).AddTicks(8729),
                            Status = 1
                        },
                        new
                        {
                            ID = 26,
                            InsertedDate = new DateTime(2022, 3, 19, 20, 10, 31, 486, DateTimeKind.Unspecified).AddTicks(821),
                            MadeIn = "Poland",
                            RealeseDate = new DateTime(2021, 6, 1, 7, 18, 1, 343, DateTimeKind.Unspecified).AddTicks(2178),
                            Status = 1
                        },
                        new
                        {
                            ID = 27,
                            InsertedDate = new DateTime(2022, 11, 16, 9, 46, 36, 882, DateTimeKind.Unspecified).AddTicks(671),
                            MadeIn = "Suriname",
                            RealeseDate = new DateTime(2021, 7, 8, 10, 56, 50, 366, DateTimeKind.Unspecified).AddTicks(2752),
                            Status = 1
                        },
                        new
                        {
                            ID = 28,
                            InsertedDate = new DateTime(2022, 7, 18, 10, 37, 18, 445, DateTimeKind.Unspecified).AddTicks(7806),
                            MadeIn = "Sierra Leone",
                            RealeseDate = new DateTime(2022, 7, 8, 7, 59, 9, 461, DateTimeKind.Unspecified).AddTicks(9934),
                            Status = 1
                        },
                        new
                        {
                            ID = 29,
                            InsertedDate = new DateTime(2022, 6, 17, 21, 33, 51, 785, DateTimeKind.Unspecified).AddTicks(4178),
                            MadeIn = "Canada",
                            RealeseDate = new DateTime(2021, 11, 27, 21, 0, 19, 199, DateTimeKind.Unspecified).AddTicks(4973),
                            Status = 1
                        },
                        new
                        {
                            ID = 30,
                            InsertedDate = new DateTime(2022, 9, 2, 8, 2, 50, 379, DateTimeKind.Unspecified).AddTicks(3427),
                            MadeIn = "Western Sahara",
                            RealeseDate = new DateTime(2022, 10, 3, 19, 16, 24, 845, DateTimeKind.Unspecified).AddTicks(9995),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductSupplier", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCountPerShipping")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductsSuppliers");

                    b.HasData(
                        new
                        {
                            ProductID = 9,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 4, 26, 13, 59, 8, 159, DateTimeKind.Unspecified).AddTicks(185),
                            MaxCountPerShipping = 98,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 8, 8, 21, 22, 50, 837, DateTimeKind.Unspecified).AddTicks(8269),
                            MaxCountPerShipping = 195,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 8, 23, 17, 38, 33, 629, DateTimeKind.Unspecified).AddTicks(3578),
                            MaxCountPerShipping = 44,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 8, 3, 20, 26, 45, 339, DateTimeKind.Unspecified).AddTicks(5882),
                            MaxCountPerShipping = 23,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 1,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 1, 19, 1, 35, 33, 954, DateTimeKind.Unspecified).AddTicks(8798),
                            MaxCountPerShipping = 142,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2022, 7, 11, 14, 55, 35, 171, DateTimeKind.Unspecified).AddTicks(5089),
                            MaxCountPerShipping = 27,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 30,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2021, 4, 5, 12, 44, 54, 573, DateTimeKind.Unspecified).AddTicks(7015),
                            MaxCountPerShipping = 117,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2021, 5, 5, 1, 13, 48, 403, DateTimeKind.Unspecified).AddTicks(8626),
                            MaxCountPerShipping = 164,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2022, 10, 1, 23, 46, 25, 553, DateTimeKind.Unspecified).AddTicks(3485),
                            MaxCountPerShipping = 45,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 11, 17, 4, 29, 34, 323, DateTimeKind.Unspecified).AddTicks(4137),
                            MaxCountPerShipping = 162,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2022, 5, 17, 9, 17, 44, 576, DateTimeKind.Unspecified).AddTicks(5505),
                            MaxCountPerShipping = 111,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 1,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 10, 15, 9, 23, 58, 709, DateTimeKind.Unspecified).AddTicks(2654),
                            MaxCountPerShipping = 80,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 7, 29, 0, 59, 46, 762, DateTimeKind.Unspecified).AddTicks(3602),
                            MaxCountPerShipping = 92,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 9, 7, 14, 21, 1, 402, DateTimeKind.Unspecified).AddTicks(8879),
                            MaxCountPerShipping = 42,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2021, 12, 30, 18, 40, 50, 606, DateTimeKind.Unspecified).AddTicks(8576),
                            MaxCountPerShipping = 69,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 18,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2021, 8, 20, 17, 40, 40, 795, DateTimeKind.Unspecified).AddTicks(949),
                            MaxCountPerShipping = 71,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2022, 2, 12, 2, 52, 45, 870, DateTimeKind.Unspecified).AddTicks(5653),
                            MaxCountPerShipping = 56,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 1,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 4, 6, 0, 23, 14, 485, DateTimeKind.Unspecified).AddTicks(6605),
                            MaxCountPerShipping = 33,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 12, 5, 4, 16, 51, 290, DateTimeKind.Unspecified).AddTicks(631),
                            MaxCountPerShipping = 172,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 7, 18, 2, 43, 43, 394, DateTimeKind.Unspecified).AddTicks(9303),
                            MaxCountPerShipping = 200,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 4, 4, 23, 36, 33, 401, DateTimeKind.Unspecified).AddTicks(9515),
                            MaxCountPerShipping = 78,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 4,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 6, 5, 17, 16, 24, 365, DateTimeKind.Unspecified).AddTicks(3370),
                            MaxCountPerShipping = 134,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 18,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 11, 3, 7, 18, 42, 221, DateTimeKind.Unspecified).AddTicks(6107),
                            MaxCountPerShipping = 40,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2022, 1, 13, 8, 7, 1, 121, DateTimeKind.Unspecified).AddTicks(7472),
                            MaxCountPerShipping = 14,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 27,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 12, 6, 16, 16, 57, 969, DateTimeKind.Unspecified).AddTicks(6501),
                            MaxCountPerShipping = 71,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 21,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2021, 7, 28, 23, 3, 48, 822, DateTimeKind.Unspecified).AddTicks(4799),
                            MaxCountPerShipping = 95,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 27,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 1, 11, 14, 31, 2, 942, DateTimeKind.Unspecified).AddTicks(5708),
                            MaxCountPerShipping = 8,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 7, 22, 2, 42, 29, 315, DateTimeKind.Unspecified).AddTicks(6986),
                            MaxCountPerShipping = 136,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 12, 22, 9, 11, 51, 526, DateTimeKind.Unspecified).AddTicks(7558),
                            MaxCountPerShipping = 156,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 23,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2022, 6, 27, 18, 34, 52, 441, DateTimeKind.Unspecified).AddTicks(9952),
                            MaxCountPerShipping = 187,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2021, 12, 24, 21, 59, 47, 534, DateTimeKind.Unspecified).AddTicks(4915),
                            MaxCountPerShipping = 63,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 22,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 3, 30, 6, 24, 30, 488, DateTimeKind.Unspecified).AddTicks(6075),
                            MaxCountPerShipping = 157,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 5, 7, 20, 57, 36, 262, DateTimeKind.Unspecified).AddTicks(560),
                            MaxCountPerShipping = 42,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 5, 2, 4, 6, 1, 45, DateTimeKind.Unspecified).AddTicks(9640),
                            MaxCountPerShipping = 84,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 3,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 10, 22, 7, 20, 44, 465, DateTimeKind.Unspecified).AddTicks(8366),
                            MaxCountPerShipping = 193,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 1, 15, 10, 27, 41, 330, DateTimeKind.Unspecified).AddTicks(1094),
                            MaxCountPerShipping = 113,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 4, 5, 1, 29, 49, 500, DateTimeKind.Unspecified).AddTicks(1409),
                            MaxCountPerShipping = 156,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 22,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 12, 31, 18, 27, 9, 48, DateTimeKind.Unspecified).AddTicks(8028),
                            MaxCountPerShipping = 183,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 9, 23, 3, 28, 33, 106, DateTimeKind.Unspecified).AddTicks(7597),
                            MaxCountPerShipping = 110,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 10, 29, 12, 21, 21, 260, DateTimeKind.Unspecified).AddTicks(9248),
                            MaxCountPerShipping = 89,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 11, 30, 8, 14, 29, 902, DateTimeKind.Unspecified).AddTicks(2981),
                            MaxCountPerShipping = 161,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2021, 7, 26, 1, 11, 51, 407, DateTimeKind.Unspecified).AddTicks(329),
                            MaxCountPerShipping = 167,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 5, 5, 23, 18, 35, 449, DateTimeKind.Unspecified).AddTicks(4019),
                            MaxCountPerShipping = 113,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 10, 27, 18, 44, 50, 684, DateTimeKind.Unspecified).AddTicks(7292),
                            MaxCountPerShipping = 138,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 7,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 10, 14, 3, 4, 42, 621, DateTimeKind.Unspecified).AddTicks(4585),
                            MaxCountPerShipping = 127,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 3, 14, 21, 12, 21, 728, DateTimeKind.Unspecified).AddTicks(8740),
                            MaxCountPerShipping = 120,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 4, 22, 8, 11, 41, 315, DateTimeKind.Unspecified).AddTicks(933),
                            MaxCountPerShipping = 9,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 12, 1, 19, 47, 48, 278, DateTimeKind.Unspecified).AddTicks(8415),
                            MaxCountPerShipping = 131,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 6, 11, 2, 26, 50, 721, DateTimeKind.Unspecified).AddTicks(7788),
                            MaxCountPerShipping = 109,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 1, 26, 17, 40, 27, 927, DateTimeKind.Unspecified).AddTicks(6055),
                            MaxCountPerShipping = 115,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 10,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 5, 3, 10, 59, 55, 741, DateTimeKind.Unspecified).AddTicks(1366),
                            MaxCountPerShipping = 72,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 21,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 10, 10, 6, 29, 39, 106, DateTimeKind.Unspecified).AddTicks(5574),
                            MaxCountPerShipping = 21,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 30,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 9, 8, 15, 46, 5, 66, DateTimeKind.Unspecified).AddTicks(2213),
                            MaxCountPerShipping = 131,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2022, 2, 21, 3, 32, 1, 928, DateTimeKind.Unspecified).AddTicks(5202),
                            MaxCountPerShipping = 78,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 5, 31, 5, 11, 5, 980, DateTimeKind.Unspecified).AddTicks(8451),
                            MaxCountPerShipping = 142,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 9, 23, 22, 5, 21, 455, DateTimeKind.Unspecified).AddTicks(9676),
                            MaxCountPerShipping = 19,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 6, 13, 21, 8, 50, 754, DateTimeKind.Unspecified).AddTicks(6811),
                            MaxCountPerShipping = 65,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 9,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 2, 5, 9, 59, 42, 573, DateTimeKind.Unspecified).AddTicks(7872),
                            MaxCountPerShipping = 199,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 7, 13, 14, 11, 29, 306, DateTimeKind.Unspecified).AddTicks(3458),
                            MaxCountPerShipping = 166,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 7,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 6, 27, 0, 3, 41, 406, DateTimeKind.Unspecified).AddTicks(6156),
                            MaxCountPerShipping = 25,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 6, 20, 3, 49, 22, 744, DateTimeKind.Unspecified).AddTicks(2144),
                            MaxCountPerShipping = 163,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 13,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 2, 22, 1, 13, 2, 437, DateTimeKind.Unspecified).AddTicks(9137),
                            MaxCountPerShipping = 134,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 10, 18, 6, 6, 46, 65, DateTimeKind.Unspecified).AddTicks(9190),
                            MaxCountPerShipping = 97,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 10, 12, 21, 56, 51, 271, DateTimeKind.Unspecified).AddTicks(9418),
                            MaxCountPerShipping = 13,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 12, 8, 10, 45, 31, 41, DateTimeKind.Unspecified).AddTicks(3677),
                            MaxCountPerShipping = 7,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 7, 20, 13, 42, 41, 631, DateTimeKind.Unspecified).AddTicks(609),
                            MaxCountPerShipping = 75,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 1, 25, 14, 21, 43, 200, DateTimeKind.Unspecified).AddTicks(877),
                            MaxCountPerShipping = 197,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 9,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 4, 8, 16, 2, 7, 558, DateTimeKind.Unspecified).AddTicks(2738),
                            MaxCountPerShipping = 58,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 6,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 6, 18, 22, 29, 49, 787, DateTimeKind.Unspecified).AddTicks(4524),
                            MaxCountPerShipping = 1,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 8, 28, 17, 2, 9, 267, DateTimeKind.Unspecified).AddTicks(1825),
                            MaxCountPerShipping = 127,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 11, 6, 1, 56, 6, 495, DateTimeKind.Unspecified).AddTicks(2632),
                            MaxCountPerShipping = 135,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 18,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 12, 28, 12, 46, 22, 91, DateTimeKind.Unspecified).AddTicks(3681),
                            MaxCountPerShipping = 35,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 8, 8, 15, 50, 42, 400, DateTimeKind.Unspecified).AddTicks(1463),
                            MaxCountPerShipping = 197,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 6,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 11, 2, 7, 31, 47, 613, DateTimeKind.Unspecified).AddTicks(1734),
                            MaxCountPerShipping = 62,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 11, 14, 20, 39, 12, 611, DateTimeKind.Unspecified).AddTicks(1320),
                            MaxCountPerShipping = 3,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 1,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 1, 20, 14, 51, 12, 843, DateTimeKind.Unspecified).AddTicks(5543),
                            MaxCountPerShipping = 40,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 3,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2021, 8, 22, 2, 24, 38, 315, DateTimeKind.Unspecified).AddTicks(3868),
                            MaxCountPerShipping = 70,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2021, 8, 9, 11, 0, 14, 951, DateTimeKind.Unspecified).AddTicks(415),
                            MaxCountPerShipping = 56,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 30,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2022, 3, 21, 6, 1, 10, 386, DateTimeKind.Unspecified).AddTicks(6926),
                            MaxCountPerShipping = 132,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 5, 29, 23, 21, 55, 632, DateTimeKind.Unspecified).AddTicks(545),
                            MaxCountPerShipping = 25,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 19,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2022, 9, 15, 16, 23, 43, 378, DateTimeKind.Unspecified).AddTicks(1032),
                            MaxCountPerShipping = 52,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 11, 3, 3, 21, 25, 842, DateTimeKind.Unspecified).AddTicks(5793),
                            MaxCountPerShipping = 46,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 7, 17, 8, 41, 30, 149, DateTimeKind.Unspecified).AddTicks(9083),
                            MaxCountPerShipping = 148,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 3,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 12, 17, 1, 35, 34, 816, DateTimeKind.Unspecified).AddTicks(3401),
                            MaxCountPerShipping = 45,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 6, 26, 21, 37, 59, 761, DateTimeKind.Unspecified).AddTicks(9231),
                            MaxCountPerShipping = 26,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 9, 29, 3, 17, 0, 768, DateTimeKind.Unspecified).AddTicks(3213),
                            MaxCountPerShipping = 163,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 30,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 3, 24, 13, 53, 30, 552, DateTimeKind.Unspecified).AddTicks(2460),
                            MaxCountPerShipping = 57,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyName = "Kub Inc",
                            InsertedDate = new DateTime(2022, 3, 22, 19, 14, 25, 618, DateTimeKind.Unspecified).AddTicks(5595),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CompanyName = "Weissnat and Sons",
                            InsertedDate = new DateTime(2022, 9, 8, 9, 43, 30, 331, DateTimeKind.Unspecified).AddTicks(7513),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CompanyName = "Predovic, Hintz and Borer",
                            InsertedDate = new DateTime(2021, 7, 21, 17, 59, 43, 99, DateTimeKind.Unspecified).AddTicks(7884),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CompanyName = "Keeling, Smitham and Raynor",
                            InsertedDate = new DateTime(2021, 5, 1, 23, 32, 15, 287, DateTimeKind.Unspecified).AddTicks(6255),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CompanyName = "Klein - Shields",
                            InsertedDate = new DateTime(2021, 9, 13, 8, 28, 17, 897, DateTimeKind.Unspecified).AddTicks(2501),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CompanyName = "Becker - Doyle",
                            InsertedDate = new DateTime(2021, 6, 19, 0, 31, 3, 62, DateTimeKind.Unspecified).AddTicks(9908),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CompanyName = "Jenkins and Sons",
                            InsertedDate = new DateTime(2022, 5, 31, 15, 15, 49, 716, DateTimeKind.Unspecified).AddTicks(1775),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CompanyName = "Stoltenberg, Tillman and Barrows",
                            InsertedDate = new DateTime(2022, 7, 3, 23, 28, 35, 478, DateTimeKind.Unspecified).AddTicks(8817),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CompanyName = "Lockman - Boehm",
                            InsertedDate = new DateTime(2022, 1, 20, 16, 22, 28, 441, DateTimeKind.Unspecified).AddTicks(5232),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CompanyName = "Huels LLC",
                            InsertedDate = new DateTime(2022, 3, 14, 1, 33, 5, 98, DateTimeKind.Unspecified).AddTicks(7502),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductSupplier", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.Navigation("ProductFeature")
                        .IsRequired();

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
