// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueOnion.PERSISTINCE.Context;

#nullable disable

namespace TrueOnion.PERSISTINCE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221226221636_myMig")]
    partial class myMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "All",
                            InsertedDate = new DateTime(2021, 12, 15, 10, 39, 27, 595, DateTimeKind.Unspecified).AddTicks(3566),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Jewelery",
                            InsertedDate = new DateTime(2021, 5, 16, 9, 57, 16, 522, DateTimeKind.Unspecified).AddTicks(3575),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Music",
                            InsertedDate = new DateTime(2020, 10, 14, 7, 22, 38, 334, DateTimeKind.Unspecified).AddTicks(1724),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Health",
                            InsertedDate = new DateTime(2021, 11, 16, 8, 17, 23, 26, DateTimeKind.Unspecified).AddTicks(1312),
                            ParentID = 2,
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Jewelery",
                            InsertedDate = new DateTime(2022, 10, 21, 9, 0, 20, 237, DateTimeKind.Unspecified).AddTicks(7910),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Home",
                            InsertedDate = new DateTime(2020, 10, 17, 2, 7, 29, 599, DateTimeKind.Unspecified).AddTicks(113),
                            ParentID = 4,
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Kids",
                            InsertedDate = new DateTime(2021, 1, 3, 12, 57, 18, 637, DateTimeKind.Unspecified).AddTicks(4534),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Automotive",
                            InsertedDate = new DateTime(2020, 6, 21, 17, 49, 56, 278, DateTimeKind.Unspecified).AddTicks(2337),
                            ParentID = 7,
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Beauty",
                            InsertedDate = new DateTime(2020, 7, 15, 11, 42, 38, 736, DateTimeKind.Unspecified).AddTicks(6861),
                            ParentID = 1,
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Books",
                            InsertedDate = new DateTime(2022, 12, 6, 5, 8, 15, 119, DateTimeKind.Unspecified).AddTicks(1152),
                            ParentID = 9,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2020, 3, 23, 6, 8, 48, 876, DateTimeKind.Unspecified).AddTicks(6389),
                            Name = "Generic Rubber Fish",
                            Price = 56m,
                            Status = 1,
                            Stock = 101
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 3, 21, 23, 38, 58, 265, DateTimeKind.Unspecified).AddTicks(2181),
                            Name = "Incredible Metal Bike",
                            Price = 55m,
                            Status = 1,
                            Stock = 172
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 5, 15, 14, 3, 32, 259, DateTimeKind.Unspecified).AddTicks(4080),
                            Name = "Handcrafted Frozen Ball",
                            Price = 52m,
                            Status = 1,
                            Stock = 149
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2020, 5, 28, 18, 2, 35, 115, DateTimeKind.Unspecified).AddTicks(5804),
                            Name = "Handcrafted Plastic Mouse",
                            Price = 56m,
                            Status = 1,
                            Stock = 195
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2020, 10, 22, 14, 34, 23, 86, DateTimeKind.Unspecified).AddTicks(1126),
                            Name = "Practical Granite Chips",
                            Price = 57m,
                            Status = 1,
                            Stock = 181
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2021, 1, 27, 8, 37, 2, 839, DateTimeKind.Unspecified).AddTicks(7135),
                            Name = "Small Wooden Tuna",
                            Price = 52m,
                            Status = 1,
                            Stock = 110
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 12, 20, 23, 32, 42, 513, DateTimeKind.Unspecified).AddTicks(3060),
                            Name = "Refined Soft Keyboard",
                            Price = 50m,
                            Status = 1,
                            Stock = 137
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2020, 3, 28, 14, 40, 11, 871, DateTimeKind.Unspecified).AddTicks(5669),
                            Name = "Handcrafted Cotton Towels",
                            Price = 49m,
                            Status = 1,
                            Stock = 52
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2020, 9, 7, 15, 51, 0, 943, DateTimeKind.Unspecified).AddTicks(2031),
                            Name = "Refined Rubber Soap",
                            Price = 54m,
                            Status = 1,
                            Stock = 35
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2022, 12, 1, 20, 20, 2, 171, DateTimeKind.Unspecified).AddTicks(549),
                            Name = "Practical Frozen Chicken",
                            Price = 57m,
                            Status = 1,
                            Stock = 36
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 2, 20, 14, 52, 52, 207, DateTimeKind.Unspecified).AddTicks(3955),
                            Name = "Practical Steel Chair",
                            Price = 54m,
                            Status = 1,
                            Stock = 34
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2020, 10, 5, 13, 35, 5, 32, DateTimeKind.Unspecified).AddTicks(823),
                            Name = "Ergonomic Cotton Pants",
                            Price = 52m,
                            Status = 1,
                            Stock = 110
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2021, 9, 29, 18, 54, 49, 307, DateTimeKind.Unspecified).AddTicks(4449),
                            Name = "Sleek Granite Computer",
                            Price = 54m,
                            Status = 1,
                            Stock = 37
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 10, 19, 7, 40, 19, 69, DateTimeKind.Unspecified).AddTicks(1744),
                            Name = "Unbranded Granite Shirt",
                            Price = 55m,
                            Status = 1,
                            Stock = 78
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2020, 9, 4, 23, 29, 42, 28, DateTimeKind.Unspecified).AddTicks(330),
                            Name = "Sleek Metal Gloves",
                            Price = 53m,
                            Status = 1,
                            Stock = 110
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 3, 8, 12, 15, 56, 600, DateTimeKind.Unspecified).AddTicks(1643),
                            Name = "Small Plastic Cheese",
                            Price = 52m,
                            Status = 1,
                            Stock = 170
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 12, 26, 21, 36, 54, 610, DateTimeKind.Unspecified).AddTicks(8655),
                            Name = "Refined Fresh Bacon",
                            Price = 57m,
                            Status = 1,
                            Stock = 15
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2021, 5, 8, 17, 51, 47, 630, DateTimeKind.Unspecified).AddTicks(1711),
                            Name = "Unbranded Soft Sausages",
                            Price = 52m,
                            Status = 1,
                            Stock = 16
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 12, 6, 20, 56, 19, 26, DateTimeKind.Unspecified).AddTicks(8456),
                            Name = "Gorgeous Cotton Mouse",
                            Price = 49m,
                            Status = 1,
                            Stock = 115
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 11, 4, 14, 11, 11, 662, DateTimeKind.Unspecified).AddTicks(5713),
                            Name = "Awesome Frozen Gloves",
                            Price = 50m,
                            Status = 1,
                            Stock = 154
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 6, 18, 20, 56, 11, 925, DateTimeKind.Unspecified).AddTicks(2705),
                            Name = "Sleek Concrete Cheese",
                            Price = 50m,
                            Status = 1,
                            Stock = 96
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 3, 12, 9, 34, 11, 386, DateTimeKind.Unspecified).AddTicks(7246),
                            Name = "Ergonomic Rubber Computer",
                            Price = 57m,
                            Status = 1,
                            Stock = 22
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2020, 6, 3, 5, 49, 51, 456, DateTimeKind.Unspecified).AddTicks(8126),
                            Name = "Intelligent Soft Table",
                            Price = 53m,
                            Status = 1,
                            Stock = 175
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2020, 6, 23, 8, 22, 48, 135, DateTimeKind.Unspecified).AddTicks(5762),
                            Name = "Incredible Frozen Table",
                            Price = 53m,
                            Status = 1,
                            Stock = 195
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2020, 9, 4, 7, 31, 20, 210, DateTimeKind.Unspecified).AddTicks(3674),
                            Name = "Tasty Wooden Keyboard",
                            Price = 55m,
                            Status = 1,
                            Stock = 6
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2022, 9, 21, 1, 19, 30, 50, DateTimeKind.Unspecified).AddTicks(8704),
                            Name = "Generic Metal Bacon",
                            Price = 54m,
                            Status = 1,
                            Stock = 191
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2022, 3, 24, 21, 53, 23, 696, DateTimeKind.Unspecified).AddTicks(5676),
                            Name = "Sleek Frozen Tuna",
                            Price = 52m,
                            Status = 1,
                            Stock = 26
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2022, 8, 28, 11, 15, 49, 262, DateTimeKind.Unspecified).AddTicks(9488),
                            Name = "Awesome Concrete Computer",
                            Price = 56m,
                            Status = 1,
                            Stock = 36
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2020, 7, 18, 16, 18, 55, 945, DateTimeKind.Unspecified).AddTicks(7642),
                            Name = "Licensed Rubber Pizza",
                            Price = 56m,
                            Status = 1,
                            Stock = 106
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2021, 6, 3, 0, 59, 18, 85, DateTimeKind.Unspecified).AddTicks(652),
                            Name = "Generic Plastic Mouse",
                            Price = 53m,
                            Status = 1,
                            Stock = 105
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MadeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RelaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductFeatures");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InsertedDate = new DateTime(2020, 5, 20, 10, 12, 50, 373, DateTimeKind.Unspecified).AddTicks(93),
                            MadeIn = "Burkina Faso",
                            RelaseDate = new DateTime(2022, 11, 10, 3, 54, 36, 724, DateTimeKind.Unspecified).AddTicks(65),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            InsertedDate = new DateTime(2022, 9, 12, 6, 42, 36, 945, DateTimeKind.Unspecified).AddTicks(6885),
                            MadeIn = "Solomon Islands",
                            RelaseDate = new DateTime(2020, 10, 29, 0, 42, 3, 980, DateTimeKind.Unspecified).AddTicks(6948),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            InsertedDate = new DateTime(2020, 12, 14, 7, 2, 1, 597, DateTimeKind.Unspecified).AddTicks(4534),
                            MadeIn = "Mauritania",
                            RelaseDate = new DateTime(2022, 9, 7, 0, 26, 12, 543, DateTimeKind.Unspecified).AddTicks(7959),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            InsertedDate = new DateTime(2020, 7, 11, 16, 40, 45, 423, DateTimeKind.Unspecified).AddTicks(5384),
                            MadeIn = "Holy See (Vatican City State)",
                            RelaseDate = new DateTime(2021, 4, 6, 14, 27, 36, 508, DateTimeKind.Unspecified).AddTicks(7076),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            InsertedDate = new DateTime(2021, 1, 9, 23, 46, 0, 166, DateTimeKind.Unspecified).AddTicks(3874),
                            MadeIn = "Macedonia",
                            RelaseDate = new DateTime(2020, 3, 24, 9, 11, 38, 588, DateTimeKind.Unspecified).AddTicks(2776),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            InsertedDate = new DateTime(2021, 10, 2, 6, 21, 40, 277, DateTimeKind.Unspecified).AddTicks(454),
                            MadeIn = "Australia",
                            RelaseDate = new DateTime(2022, 11, 22, 18, 52, 42, 357, DateTimeKind.Unspecified).AddTicks(2041),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            InsertedDate = new DateTime(2021, 5, 11, 10, 46, 39, 130, DateTimeKind.Unspecified).AddTicks(5410),
                            MadeIn = "British Indian Ocean Territory (Chagos Archipelago)",
                            RelaseDate = new DateTime(2022, 12, 16, 15, 48, 0, 316, DateTimeKind.Unspecified).AddTicks(4771),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            InsertedDate = new DateTime(2021, 3, 11, 16, 17, 32, 884, DateTimeKind.Unspecified).AddTicks(9378),
                            MadeIn = "Guam",
                            RelaseDate = new DateTime(2021, 3, 27, 19, 26, 52, 16, DateTimeKind.Unspecified).AddTicks(4845),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            InsertedDate = new DateTime(2020, 7, 20, 10, 8, 1, 330, DateTimeKind.Unspecified).AddTicks(8179),
                            MadeIn = "Cameroon",
                            RelaseDate = new DateTime(2020, 11, 14, 9, 43, 58, 9, DateTimeKind.Unspecified).AddTicks(1569),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            InsertedDate = new DateTime(2020, 9, 30, 13, 38, 45, 961, DateTimeKind.Unspecified).AddTicks(8165),
                            MadeIn = "Cyprus",
                            RelaseDate = new DateTime(2021, 12, 14, 18, 55, 44, 690, DateTimeKind.Unspecified).AddTicks(9374),
                            Status = 1
                        },
                        new
                        {
                            ID = 11,
                            InsertedDate = new DateTime(2022, 8, 1, 23, 50, 54, 413, DateTimeKind.Unspecified).AddTicks(7051),
                            MadeIn = "Solomon Islands",
                            RelaseDate = new DateTime(2021, 1, 12, 6, 37, 50, 101, DateTimeKind.Unspecified).AddTicks(8146),
                            Status = 1
                        },
                        new
                        {
                            ID = 12,
                            InsertedDate = new DateTime(2021, 8, 4, 8, 55, 19, 862, DateTimeKind.Unspecified).AddTicks(4538),
                            MadeIn = "Montserrat",
                            RelaseDate = new DateTime(2022, 8, 20, 0, 3, 13, 269, DateTimeKind.Unspecified).AddTicks(1434),
                            Status = 1
                        },
                        new
                        {
                            ID = 13,
                            InsertedDate = new DateTime(2022, 8, 15, 9, 47, 53, 245, DateTimeKind.Unspecified).AddTicks(3263),
                            MadeIn = "Hungary",
                            RelaseDate = new DateTime(2021, 1, 8, 20, 4, 59, 734, DateTimeKind.Unspecified).AddTicks(5440),
                            Status = 1
                        },
                        new
                        {
                            ID = 14,
                            InsertedDate = new DateTime(2022, 12, 16, 20, 16, 26, 646, DateTimeKind.Unspecified).AddTicks(5763),
                            MadeIn = "French Polynesia",
                            RelaseDate = new DateTime(2020, 3, 30, 9, 28, 4, 686, DateTimeKind.Unspecified).AddTicks(6589),
                            Status = 1
                        },
                        new
                        {
                            ID = 15,
                            InsertedDate = new DateTime(2021, 10, 18, 22, 37, 13, 494, DateTimeKind.Unspecified).AddTicks(1024),
                            MadeIn = "Norway",
                            RelaseDate = new DateTime(2020, 8, 24, 2, 57, 4, 784, DateTimeKind.Unspecified).AddTicks(152),
                            Status = 1
                        },
                        new
                        {
                            ID = 16,
                            InsertedDate = new DateTime(2021, 8, 4, 19, 16, 47, 864, DateTimeKind.Unspecified).AddTicks(7786),
                            MadeIn = "Haiti",
                            RelaseDate = new DateTime(2022, 3, 12, 14, 18, 2, 147, DateTimeKind.Unspecified).AddTicks(4255),
                            Status = 1
                        },
                        new
                        {
                            ID = 17,
                            InsertedDate = new DateTime(2022, 1, 14, 6, 2, 52, 620, DateTimeKind.Unspecified).AddTicks(7072),
                            MadeIn = "Holy See (Vatican City State)",
                            RelaseDate = new DateTime(2022, 1, 22, 17, 44, 44, 527, DateTimeKind.Unspecified).AddTicks(9616),
                            Status = 1
                        },
                        new
                        {
                            ID = 18,
                            InsertedDate = new DateTime(2020, 3, 19, 22, 0, 0, 906, DateTimeKind.Unspecified).AddTicks(2309),
                            MadeIn = "Bangladesh",
                            RelaseDate = new DateTime(2022, 5, 27, 19, 16, 30, 652, DateTimeKind.Unspecified).AddTicks(2579),
                            Status = 1
                        },
                        new
                        {
                            ID = 19,
                            InsertedDate = new DateTime(2022, 5, 2, 11, 28, 27, 752, DateTimeKind.Unspecified).AddTicks(6427),
                            MadeIn = "Svalbard & Jan Mayen Islands",
                            RelaseDate = new DateTime(2022, 10, 29, 5, 25, 28, 928, DateTimeKind.Unspecified).AddTicks(6092),
                            Status = 1
                        },
                        new
                        {
                            ID = 20,
                            InsertedDate = new DateTime(2021, 9, 28, 0, 1, 14, 651, DateTimeKind.Unspecified).AddTicks(73),
                            MadeIn = "Belgium",
                            RelaseDate = new DateTime(2020, 3, 24, 16, 46, 19, 821, DateTimeKind.Unspecified).AddTicks(8504),
                            Status = 1
                        },
                        new
                        {
                            ID = 21,
                            InsertedDate = new DateTime(2021, 7, 4, 17, 27, 16, 34, DateTimeKind.Unspecified).AddTicks(6707),
                            MadeIn = "Malawi",
                            RelaseDate = new DateTime(2021, 3, 6, 17, 59, 55, 582, DateTimeKind.Unspecified).AddTicks(6675),
                            Status = 1
                        },
                        new
                        {
                            ID = 22,
                            InsertedDate = new DateTime(2022, 9, 27, 7, 33, 45, 622, DateTimeKind.Unspecified).AddTicks(9857),
                            MadeIn = "Guam",
                            RelaseDate = new DateTime(2021, 5, 7, 2, 35, 42, 515, DateTimeKind.Unspecified).AddTicks(1869),
                            Status = 1
                        },
                        new
                        {
                            ID = 23,
                            InsertedDate = new DateTime(2021, 1, 1, 22, 9, 42, 28, DateTimeKind.Unspecified).AddTicks(3879),
                            MadeIn = "Solomon Islands",
                            RelaseDate = new DateTime(2021, 5, 9, 10, 41, 38, 216, DateTimeKind.Unspecified).AddTicks(6471),
                            Status = 1
                        },
                        new
                        {
                            ID = 24,
                            InsertedDate = new DateTime(2020, 12, 17, 17, 56, 14, 120, DateTimeKind.Unspecified).AddTicks(2080),
                            MadeIn = "Aruba",
                            RelaseDate = new DateTime(2022, 10, 23, 11, 10, 25, 867, DateTimeKind.Unspecified).AddTicks(1286),
                            Status = 1
                        },
                        new
                        {
                            ID = 25,
                            InsertedDate = new DateTime(2022, 1, 17, 22, 6, 4, 199, DateTimeKind.Unspecified).AddTicks(8755),
                            MadeIn = "Jamaica",
                            RelaseDate = new DateTime(2021, 10, 1, 16, 45, 32, 455, DateTimeKind.Unspecified).AddTicks(253),
                            Status = 1
                        },
                        new
                        {
                            ID = 26,
                            InsertedDate = new DateTime(2021, 11, 24, 0, 45, 39, 85, DateTimeKind.Unspecified).AddTicks(2340),
                            MadeIn = "Malawi",
                            RelaseDate = new DateTime(2021, 7, 25, 3, 45, 9, 993, DateTimeKind.Unspecified).AddTicks(4288),
                            Status = 1
                        },
                        new
                        {
                            ID = 27,
                            InsertedDate = new DateTime(2020, 11, 24, 13, 57, 24, 137, DateTimeKind.Unspecified).AddTicks(8993),
                            MadeIn = "Burundi",
                            RelaseDate = new DateTime(2020, 7, 15, 15, 24, 49, 984, DateTimeKind.Unspecified).AddTicks(9804),
                            Status = 1
                        },
                        new
                        {
                            ID = 28,
                            InsertedDate = new DateTime(2022, 10, 27, 3, 55, 4, 511, DateTimeKind.Unspecified).AddTicks(4009),
                            MadeIn = "Indonesia",
                            RelaseDate = new DateTime(2020, 12, 26, 9, 2, 37, 849, DateTimeKind.Unspecified).AddTicks(3485),
                            Status = 1
                        },
                        new
                        {
                            ID = 29,
                            InsertedDate = new DateTime(2021, 4, 15, 16, 35, 54, 688, DateTimeKind.Unspecified).AddTicks(9342),
                            MadeIn = "Spain",
                            RelaseDate = new DateTime(2021, 4, 6, 19, 59, 25, 964, DateTimeKind.Unspecified).AddTicks(983),
                            Status = 1
                        },
                        new
                        {
                            ID = 30,
                            InsertedDate = new DateTime(2021, 2, 9, 15, 41, 23, 9, DateTimeKind.Unspecified).AddTicks(3667),
                            MadeIn = "Western Sahara",
                            RelaseDate = new DateTime(2022, 9, 17, 19, 5, 36, 803, DateTimeKind.Unspecified).AddTicks(2682),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductSupplier", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCountPerShipping")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductsSuppliers");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2021, 6, 27, 5, 38, 56, 321, DateTimeKind.Unspecified).AddTicks(5170),
                            MaxCountPerShipping = 145,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2020, 12, 9, 16, 40, 14, 714, DateTimeKind.Unspecified).AddTicks(7716),
                            MaxCountPerShipping = 17,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 13,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2021, 1, 1, 15, 29, 49, 62, DateTimeKind.Unspecified).AddTicks(5260),
                            MaxCountPerShipping = 114,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 11, 24, 5, 54, 53, 769, DateTimeKind.Unspecified).AddTicks(3231),
                            MaxCountPerShipping = 151,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 1, 17, 2, 48, 31, 437, DateTimeKind.Unspecified).AddTicks(3347),
                            MaxCountPerShipping = 198,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 18,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2020, 4, 11, 19, 43, 15, 336, DateTimeKind.Unspecified).AddTicks(5378),
                            MaxCountPerShipping = 103,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2020, 11, 26, 23, 44, 42, 79, DateTimeKind.Unspecified).AddTicks(1691),
                            MaxCountPerShipping = 104,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 3,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 11, 28, 10, 27, 24, 65, DateTimeKind.Unspecified).AddTicks(1541),
                            MaxCountPerShipping = 11,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 7,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 6, 2, 8, 59, 53, 586, DateTimeKind.Unspecified).AddTicks(8745),
                            MaxCountPerShipping = 50,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2022, 10, 1, 23, 37, 18, 733, DateTimeKind.Unspecified).AddTicks(1532),
                            MaxCountPerShipping = 109,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 5, 31, 16, 51, 36, 101, DateTimeKind.Unspecified).AddTicks(8809),
                            MaxCountPerShipping = 105,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 13,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2020, 10, 10, 19, 26, 26, 341, DateTimeKind.Unspecified).AddTicks(9761),
                            MaxCountPerShipping = 84,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 13,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 9, 18, 14, 15, 45, 775, DateTimeKind.Unspecified).AddTicks(3993),
                            MaxCountPerShipping = 12,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 12, 20, 20, 23, 41, 597, DateTimeKind.Unspecified).AddTicks(678),
                            MaxCountPerShipping = 33,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 10,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2020, 10, 22, 21, 12, 49, 376, DateTimeKind.Unspecified).AddTicks(2148),
                            MaxCountPerShipping = 47,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2021, 7, 16, 9, 19, 35, 667, DateTimeKind.Unspecified).AddTicks(7619),
                            MaxCountPerShipping = 67,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 9, 7, 16, 22, 25, 487, DateTimeKind.Unspecified).AddTicks(7456),
                            MaxCountPerShipping = 135,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 9, 1, 15, 58, 1, 67, DateTimeKind.Unspecified).AddTicks(1731),
                            MaxCountPerShipping = 176,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2020, 7, 25, 0, 22, 33, 841, DateTimeKind.Unspecified).AddTicks(9960),
                            MaxCountPerShipping = 116,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2021, 7, 27, 14, 14, 55, 86, DateTimeKind.Unspecified).AddTicks(8356),
                            MaxCountPerShipping = 120,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 6,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2020, 9, 26, 3, 4, 22, 520, DateTimeKind.Unspecified).AddTicks(2758),
                            MaxCountPerShipping = 30,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 7,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2020, 9, 29, 9, 31, 17, 265, DateTimeKind.Unspecified).AddTicks(2114),
                            MaxCountPerShipping = 103,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 11, 19, 10, 21, 42, 684, DateTimeKind.Unspecified).AddTicks(7822),
                            MaxCountPerShipping = 30,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 4, 7, 6, 36, 5, 83, DateTimeKind.Unspecified).AddTicks(4983),
                            MaxCountPerShipping = 194,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 3, 8, 19, 28, 7, 707, DateTimeKind.Unspecified).AddTicks(622),
                            MaxCountPerShipping = 46,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2020, 8, 22, 2, 49, 36, 211, DateTimeKind.Unspecified).AddTicks(7624),
                            MaxCountPerShipping = 62,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 27,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2022, 11, 15, 19, 52, 27, 701, DateTimeKind.Unspecified).AddTicks(1653),
                            MaxCountPerShipping = 94,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 7, 23, 2, 27, 8, 440, DateTimeKind.Unspecified).AddTicks(823),
                            MaxCountPerShipping = 152,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 6, 8, 0, 57, 48, 49, DateTimeKind.Unspecified).AddTicks(1863),
                            MaxCountPerShipping = 122,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 7,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 2, 9, 5, 41, 5, 692, DateTimeKind.Unspecified).AddTicks(7682),
                            MaxCountPerShipping = 12,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2020, 12, 25, 14, 20, 12, 909, DateTimeKind.Unspecified).AddTicks(38),
                            MaxCountPerShipping = 105,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 19,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2022, 5, 16, 0, 56, 33, 764, DateTimeKind.Unspecified).AddTicks(6586),
                            MaxCountPerShipping = 64,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2020, 11, 13, 12, 44, 33, 293, DateTimeKind.Unspecified).AddTicks(1012),
                            MaxCountPerShipping = 103,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2022, 1, 8, 23, 23, 46, 710, DateTimeKind.Unspecified).AddTicks(7561),
                            MaxCountPerShipping = 166,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2020, 4, 16, 14, 59, 46, 822, DateTimeKind.Unspecified).AddTicks(5392),
                            MaxCountPerShipping = 31,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2020, 9, 16, 15, 1, 58, 231, DateTimeKind.Unspecified).AddTicks(8845),
                            MaxCountPerShipping = 157,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 3, 17, 23, 51, 36, 370, DateTimeKind.Unspecified).AddTicks(7972),
                            MaxCountPerShipping = 26,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2020, 9, 2, 20, 17, 48, 305, DateTimeKind.Unspecified).AddTicks(6824),
                            MaxCountPerShipping = 54,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2020, 3, 24, 17, 52, 27, 64, DateTimeKind.Unspecified).AddTicks(1908),
                            MaxCountPerShipping = 178,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2022, 1, 13, 11, 47, 46, 529, DateTimeKind.Unspecified).AddTicks(370),
                            MaxCountPerShipping = 75,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 28,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 8, 16, 2, 40, 23, 446, DateTimeKind.Unspecified).AddTicks(4482),
                            MaxCountPerShipping = 167,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 18,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 4, 21, 1, 27, 8, 769, DateTimeKind.Unspecified).AddTicks(5777),
                            MaxCountPerShipping = 33,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2020, 7, 19, 4, 49, 26, 159, DateTimeKind.Unspecified).AddTicks(4789),
                            MaxCountPerShipping = 118,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2020, 3, 31, 15, 13, 20, 916, DateTimeKind.Unspecified).AddTicks(9672),
                            MaxCountPerShipping = 51,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 3, 9, 12, 16, 17, 164, DateTimeKind.Unspecified).AddTicks(6172),
                            MaxCountPerShipping = 140,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 6,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 9, 29, 21, 41, 1, 611, DateTimeKind.Unspecified).AddTicks(696),
                            MaxCountPerShipping = 184,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2020, 5, 29, 19, 15, 8, 453, DateTimeKind.Unspecified).AddTicks(2862),
                            MaxCountPerShipping = 37,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 7, 16, 15, 52, 0, 50, DateTimeKind.Unspecified).AddTicks(9952),
                            MaxCountPerShipping = 149,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 22,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2021, 11, 19, 20, 21, 2, 803, DateTimeKind.Unspecified).AddTicks(488),
                            MaxCountPerShipping = 116,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2022, 10, 7, 1, 45, 16, 268, DateTimeKind.Unspecified).AddTicks(5210),
                            MaxCountPerShipping = 148,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2020, 5, 15, 12, 55, 18, 811, DateTimeKind.Unspecified).AddTicks(5531),
                            MaxCountPerShipping = 25,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2020, 3, 21, 2, 55, 49, 653, DateTimeKind.Unspecified).AddTicks(1565),
                            MaxCountPerShipping = 195,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 20,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 9, 13, 14, 47, 56, 570, DateTimeKind.Unspecified).AddTicks(7510),
                            MaxCountPerShipping = 21,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 4,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2022, 2, 4, 10, 55, 17, 792, DateTimeKind.Unspecified).AddTicks(1178),
                            MaxCountPerShipping = 84,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 21,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2020, 8, 20, 3, 20, 15, 730, DateTimeKind.Unspecified).AddTicks(4605),
                            MaxCountPerShipping = 173,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2021, 1, 29, 14, 41, 0, 452, DateTimeKind.Unspecified).AddTicks(4099),
                            MaxCountPerShipping = 69,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2020, 6, 20, 3, 57, 56, 400, DateTimeKind.Unspecified).AddTicks(6988),
                            MaxCountPerShipping = 180,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 25,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2021, 10, 24, 13, 42, 6, 188, DateTimeKind.Unspecified).AddTicks(888),
                            MaxCountPerShipping = 1,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 3,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2022, 2, 15, 18, 56, 48, 598, DateTimeKind.Unspecified).AddTicks(4994),
                            MaxCountPerShipping = 3,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 12,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 4, 21, 23, 24, 41, 430, DateTimeKind.Unspecified).AddTicks(5161),
                            MaxCountPerShipping = 157,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 27,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2020, 9, 9, 0, 23, 56, 356, DateTimeKind.Unspecified).AddTicks(3105),
                            MaxCountPerShipping = 168,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 21,
                            SupplierID = 9,
                            InsertedDate = new DateTime(2020, 10, 26, 1, 51, 45, 297, DateTimeKind.Unspecified).AddTicks(209),
                            MaxCountPerShipping = 166,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2021, 6, 2, 12, 3, 33, 18, DateTimeKind.Unspecified).AddTicks(3546),
                            MaxCountPerShipping = 64,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 2,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 6, 9, 13, 30, 7, 727, DateTimeKind.Unspecified).AddTicks(7186),
                            MaxCountPerShipping = 170,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2020, 5, 19, 17, 22, 36, 867, DateTimeKind.Unspecified).AddTicks(7388),
                            MaxCountPerShipping = 172,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 3, 14, 0, 44, 46, 652, DateTimeKind.Unspecified).AddTicks(5919),
                            MaxCountPerShipping = 196,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 19,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 1, 16, 0, 31, 16, 226, DateTimeKind.Unspecified).AddTicks(6020),
                            MaxCountPerShipping = 192,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 19,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2022, 8, 19, 13, 56, 35, 875, DateTimeKind.Unspecified).AddTicks(113),
                            MaxCountPerShipping = 181,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2020, 7, 18, 3, 40, 23, 285, DateTimeKind.Unspecified).AddTicks(2808),
                            MaxCountPerShipping = 159,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 5,
                            SupplierID = 10,
                            InsertedDate = new DateTime(2022, 5, 15, 18, 44, 57, 481, DateTimeKind.Unspecified).AddTicks(1384),
                            MaxCountPerShipping = 148,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 30,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2021, 3, 14, 1, 46, 59, 662, DateTimeKind.Unspecified).AddTicks(6179),
                            MaxCountPerShipping = 8,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 14,
                            SupplierID = 6,
                            InsertedDate = new DateTime(2020, 10, 24, 21, 10, 52, 873, DateTimeKind.Unspecified).AddTicks(3196),
                            MaxCountPerShipping = 34,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 6,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2020, 5, 26, 16, 49, 21, 728, DateTimeKind.Unspecified).AddTicks(8818),
                            MaxCountPerShipping = 18,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 24,
                            SupplierID = 1,
                            InsertedDate = new DateTime(2021, 11, 28, 14, 7, 27, 655, DateTimeKind.Unspecified).AddTicks(4386),
                            MaxCountPerShipping = 159,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 4,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2022, 6, 17, 11, 59, 40, 630, DateTimeKind.Unspecified).AddTicks(3978),
                            MaxCountPerShipping = 85,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 21,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2022, 11, 27, 3, 11, 47, 525, DateTimeKind.Unspecified).AddTicks(2768),
                            MaxCountPerShipping = 161,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 15,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2020, 10, 7, 18, 58, 15, 25, DateTimeKind.Unspecified).AddTicks(2619),
                            MaxCountPerShipping = 73,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 8,
                            SupplierID = 2,
                            InsertedDate = new DateTime(2021, 3, 16, 3, 54, 41, 490, DateTimeKind.Unspecified).AddTicks(8270),
                            MaxCountPerShipping = 63,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 23,
                            SupplierID = 3,
                            InsertedDate = new DateTime(2022, 8, 13, 21, 48, 27, 789, DateTimeKind.Unspecified).AddTicks(8679),
                            MaxCountPerShipping = 39,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2021, 5, 6, 10, 35, 57, 888, DateTimeKind.Unspecified).AddTicks(7544),
                            MaxCountPerShipping = 30,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 16,
                            SupplierID = 8,
                            InsertedDate = new DateTime(2020, 10, 25, 9, 31, 36, 820, DateTimeKind.Unspecified).AddTicks(2902),
                            MaxCountPerShipping = 43,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 29,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2021, 5, 31, 8, 17, 54, 546, DateTimeKind.Unspecified).AddTicks(6459),
                            MaxCountPerShipping = 70,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 26,
                            SupplierID = 7,
                            InsertedDate = new DateTime(2021, 8, 21, 14, 4, 29, 905, DateTimeKind.Unspecified).AddTicks(4544),
                            MaxCountPerShipping = 96,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 17,
                            SupplierID = 4,
                            InsertedDate = new DateTime(2021, 12, 30, 16, 33, 50, 359, DateTimeKind.Unspecified).AddTicks(469),
                            MaxCountPerShipping = 71,
                            Status = 1
                        },
                        new
                        {
                            ProductID = 11,
                            SupplierID = 5,
                            InsertedDate = new DateTime(2022, 8, 13, 13, 43, 39, 482, DateTimeKind.Unspecified).AddTicks(7184),
                            MaxCountPerShipping = 181,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyName = "Spinka LLC",
                            InsertedDate = new DateTime(2020, 7, 14, 20, 40, 34, 554, DateTimeKind.Unspecified).AddTicks(2891),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CompanyName = "Doyle Inc",
                            InsertedDate = new DateTime(2021, 9, 10, 21, 36, 2, 141, DateTimeKind.Unspecified).AddTicks(3060),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CompanyName = "Morissette Group",
                            InsertedDate = new DateTime(2020, 7, 11, 23, 9, 20, 295, DateTimeKind.Unspecified).AddTicks(7210),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CompanyName = "Rutherford - Hintz",
                            InsertedDate = new DateTime(2020, 12, 20, 11, 48, 16, 7, DateTimeKind.Unspecified).AddTicks(6612),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CompanyName = "Hagenes, Hodkiewicz and Gislason",
                            InsertedDate = new DateTime(2022, 11, 14, 16, 25, 31, 617, DateTimeKind.Unspecified).AddTicks(3253),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CompanyName = "Schmeler - Rice",
                            InsertedDate = new DateTime(2020, 12, 21, 12, 59, 46, 734, DateTimeKind.Unspecified).AddTicks(7482),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CompanyName = "Mante, Leannon and Hilll",
                            InsertedDate = new DateTime(2021, 8, 9, 16, 56, 1, 986, DateTimeKind.Unspecified).AddTicks(9081),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CompanyName = "Balistreri, Collier and Grant",
                            InsertedDate = new DateTime(2022, 11, 10, 15, 32, 31, 595, DateTimeKind.Unspecified).AddTicks(241),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CompanyName = "Batz and Sons",
                            InsertedDate = new DateTime(2020, 8, 30, 11, 12, 56, 18, DateTimeKind.Unspecified).AddTicks(9736),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CompanyName = "Jacobson - Parisian",
                            InsertedDate = new DateTime(2020, 5, 6, 0, 21, 40, 405, DateTimeKind.Unspecified).AddTicks(7667),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("TrueOnion.DOMAIN.Entities.Concrates.ProductFeature", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.ProductSupplier", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueOnion.DOMAIN.Entities.Concrates.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Product", b =>
                {
                    b.Navigation("ProductFeature")
                        .IsRequired();

                    b.Navigation("ProductSuppliers");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Concrates.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
