// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueOnion.PERSISTINCE.Context;

#nullable disable

namespace TrueOnion.PERSISTINCE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221217151512_migMonster")]
    partial class migMonster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Kids",
                            InsertedDate = new DateTime(2022, 10, 21, 19, 13, 55, 250, DateTimeKind.Unspecified).AddTicks(7196),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Computers",
                            InsertedDate = new DateTime(2022, 11, 11, 11, 10, 4, 650, DateTimeKind.Unspecified).AddTicks(9209),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Clothing",
                            InsertedDate = new DateTime(2021, 3, 23, 2, 29, 7, 589, DateTimeKind.Unspecified).AddTicks(4368),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Clothing",
                            InsertedDate = new DateTime(2022, 9, 21, 5, 1, 59, 541, DateTimeKind.Unspecified).AddTicks(279),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Baby",
                            InsertedDate = new DateTime(2021, 10, 6, 18, 1, 12, 719, DateTimeKind.Unspecified).AddTicks(9093),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Shoes",
                            InsertedDate = new DateTime(2022, 12, 17, 11, 7, 6, 818, DateTimeKind.Unspecified).AddTicks(967),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Games",
                            InsertedDate = new DateTime(2021, 11, 19, 4, 16, 39, 71, DateTimeKind.Unspecified).AddTicks(2470),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Sports",
                            InsertedDate = new DateTime(2021, 11, 8, 2, 22, 23, 358, DateTimeKind.Unspecified).AddTicks(6602),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Movies",
                            InsertedDate = new DateTime(2022, 6, 1, 17, 47, 58, 412, DateTimeKind.Unspecified).AddTicks(3775),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Games",
                            InsertedDate = new DateTime(2022, 12, 4, 5, 35, 42, 540, DateTimeKind.Unspecified).AddTicks(5366),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 9, 7, 15, 53, 6, 59, DateTimeKind.Unspecified).AddTicks(9884),
                            Name = "Generic Rubber Chicken",
                            Price = 51m,
                            Status = 1,
                            Stock = 128
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2021, 9, 25, 11, 33, 37, 631, DateTimeKind.Unspecified).AddTicks(9006),
                            Name = "Intelligent Cotton Mouse",
                            Price = 54m,
                            Status = 1,
                            Stock = 156
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 3, 10, 14, 54, 27, 175, DateTimeKind.Unspecified).AddTicks(5036),
                            Name = "Handcrafted Fresh Ball",
                            Price = 53m,
                            Status = 1,
                            Stock = 164
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2022, 9, 2, 16, 10, 0, 798, DateTimeKind.Unspecified).AddTicks(6128),
                            Name = "Intelligent Wooden Keyboard",
                            Price = 55m,
                            Status = 1,
                            Stock = 39
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2021, 5, 10, 12, 20, 27, 929, DateTimeKind.Unspecified).AddTicks(9350),
                            Name = "Tasty Wooden Mouse",
                            Price = 56m,
                            Status = 1,
                            Stock = 200
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 9, 2, 0, 1, 45, 239, DateTimeKind.Unspecified).AddTicks(9617),
                            Name = "Awesome Steel Shoes",
                            Price = 53m,
                            Status = 1,
                            Stock = 154
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2021, 6, 11, 11, 54, 29, 744, DateTimeKind.Unspecified).AddTicks(5829),
                            Name = "Handmade Wooden Soap",
                            Price = 49m,
                            Status = 1,
                            Stock = 84
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 1, 31, 15, 52, 26, 709, DateTimeKind.Unspecified).AddTicks(2429),
                            Name = "Intelligent Soft Fish",
                            Price = 55m,
                            Status = 1,
                            Stock = 172
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 9, 10, 5, 0, 26, 534, DateTimeKind.Unspecified).AddTicks(8),
                            Name = "Practical Cotton Chips",
                            Price = 50m,
                            Status = 1,
                            Stock = 143
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 3, 28, 21, 9, 48, 298, DateTimeKind.Unspecified).AddTicks(1137),
                            Name = "Handmade Frozen Chicken",
                            Price = 54m,
                            Status = 1,
                            Stock = 199
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2022, 1, 29, 10, 20, 29, 714, DateTimeKind.Unspecified).AddTicks(8169),
                            Name = "Intelligent Concrete Pizza",
                            Price = 54m,
                            Status = 1,
                            Stock = 116
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 6, 12, 9, 49, 26, 916, DateTimeKind.Unspecified).AddTicks(9834),
                            Name = "Handmade Fresh Table",
                            Price = 56m,
                            Status = 1,
                            Stock = 53
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 2, 19, 20, 38, 29, 702, DateTimeKind.Unspecified).AddTicks(4919),
                            Name = "Small Granite Shoes",
                            Price = 55m,
                            Status = 1,
                            Stock = 32
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 7, 24, 4, 30, 18, 691, DateTimeKind.Unspecified).AddTicks(7854),
                            Name = "Practical Rubber Shirt",
                            Price = 49m,
                            Status = 1,
                            Stock = 31
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 4, 5, 9, 21, 43, 465, DateTimeKind.Unspecified).AddTicks(322),
                            Name = "Sleek Cotton Salad",
                            Price = 54m,
                            Status = 1,
                            Stock = 90
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 6, 9, 1, 1, 14, 295, DateTimeKind.Unspecified).AddTicks(3582),
                            Name = "Intelligent Fresh Soap",
                            Price = 56m,
                            Status = 1,
                            Stock = 114
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2022, 7, 3, 4, 31, 11, 100, DateTimeKind.Unspecified).AddTicks(4444),
                            Name = "Licensed Concrete Towels",
                            Price = 50m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 12, 15, 8, 20, 50, 234, DateTimeKind.Unspecified).AddTicks(7913),
                            Name = "Practical Frozen Mouse",
                            Price = 51m,
                            Status = 1,
                            Stock = 184
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 8, 26, 22, 15, 20, 423, DateTimeKind.Unspecified).AddTicks(1103),
                            Name = "Generic Plastic Chair",
                            Price = 55m,
                            Status = 1,
                            Stock = 94
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 3, 31, 5, 42, 33, 16, DateTimeKind.Unspecified).AddTicks(8671),
                            Name = "Rustic Fresh Bike",
                            Price = 49m,
                            Status = 1,
                            Stock = 171
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2022, 1, 4, 6, 15, 58, 859, DateTimeKind.Unspecified).AddTicks(8234),
                            Name = "Generic Rubber Computer",
                            Price = 52m,
                            Status = 1,
                            Stock = 157
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2021, 10, 9, 8, 46, 13, 725, DateTimeKind.Unspecified).AddTicks(8432),
                            Name = "Gorgeous Frozen Chips",
                            Price = 53m,
                            Status = 1,
                            Stock = 27
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2022, 4, 3, 14, 45, 43, 414, DateTimeKind.Unspecified).AddTicks(1177),
                            Name = "Unbranded Concrete Ball",
                            Price = 51m,
                            Status = 1,
                            Stock = 176
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2022, 9, 4, 20, 43, 3, 725, DateTimeKind.Unspecified).AddTicks(6557),
                            Name = "Gorgeous Concrete Tuna",
                            Price = 49m,
                            Status = 1,
                            Stock = 71
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2022, 6, 22, 10, 26, 56, 866, DateTimeKind.Unspecified).AddTicks(4263),
                            Name = "Refined Metal Hat",
                            Price = 57m,
                            Status = 1,
                            Stock = 59
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 5, 29, 5, 38, 45, 413, DateTimeKind.Unspecified).AddTicks(1285),
                            Name = "Generic Metal Sausages",
                            Price = 52m,
                            Status = 1,
                            Stock = 82
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2022, 10, 6, 3, 8, 10, 768, DateTimeKind.Unspecified).AddTicks(8861),
                            Name = "Fantastic Steel Cheese",
                            Price = 56m,
                            Status = 1,
                            Stock = 143
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 5,
                            InsertedDate = new DateTime(2021, 5, 4, 12, 10, 12, 118, DateTimeKind.Unspecified).AddTicks(404),
                            Name = "Handmade Frozen Sausages",
                            Price = 57m,
                            Status = 1,
                            Stock = 17
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 11, 25, 10, 24, 57, 646, DateTimeKind.Unspecified).AddTicks(3605),
                            Name = "Small Cotton Soap",
                            Price = 56m,
                            Status = 1,
                            Stock = 160
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2022, 11, 11, 22, 50, 48, 931, DateTimeKind.Unspecified).AddTicks(707),
                            Name = "Practical Fresh Keyboard",
                            Price = 56m,
                            Status = 1,
                            Stock = 175
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Product", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
