// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueOnion.PERSISTINCE.Context;

#nullable disable

namespace TrueOnion.PERSISTINCE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221214194532_myNewMigration")]
    partial class myNewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Jewelery",
                            InsertedDate = new DateTime(2022, 6, 29, 18, 31, 56, 414, DateTimeKind.Unspecified).AddTicks(3050),
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Baby",
                            InsertedDate = new DateTime(2021, 9, 5, 9, 9, 39, 73, DateTimeKind.Unspecified).AddTicks(2435),
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Tools",
                            InsertedDate = new DateTime(2022, 8, 1, 12, 23, 24, 557, DateTimeKind.Unspecified).AddTicks(7576),
                            Status = 1
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Clothing",
                            InsertedDate = new DateTime(2022, 9, 26, 7, 27, 20, 84, DateTimeKind.Unspecified).AddTicks(6179),
                            Status = 1
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Games",
                            InsertedDate = new DateTime(2022, 1, 1, 23, 53, 25, 656, DateTimeKind.Unspecified).AddTicks(1339),
                            Status = 1
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Garden",
                            InsertedDate = new DateTime(2021, 9, 16, 1, 49, 35, 657, DateTimeKind.Unspecified).AddTicks(8899),
                            Status = 1
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Home",
                            InsertedDate = new DateTime(2021, 5, 17, 16, 10, 21, 512, DateTimeKind.Unspecified).AddTicks(5845),
                            Status = 1
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Games",
                            InsertedDate = new DateTime(2022, 2, 17, 8, 46, 12, 35, DateTimeKind.Unspecified).AddTicks(5396),
                            Status = 1
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Toys",
                            InsertedDate = new DateTime(2022, 12, 10, 12, 3, 9, 52, DateTimeKind.Unspecified).AddTicks(5460),
                            Status = 1
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Toys",
                            InsertedDate = new DateTime(2021, 7, 27, 12, 30, 26, 687, DateTimeKind.Unspecified).AddTicks(3658),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 7, 15, 9, 43, 47, 525, DateTimeKind.Unspecified).AddTicks(1015),
                            Name = "Handmade Fresh Bike",
                            Price = 51m,
                            Status = 1,
                            Stock = 3
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 6, 16, 3, 42, 25, 958, DateTimeKind.Unspecified).AddTicks(2942),
                            Name = "Ergonomic Granite Fish",
                            Price = 49m,
                            Status = 1,
                            Stock = 168
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2022, 4, 5, 21, 8, 16, 456, DateTimeKind.Unspecified).AddTicks(6070),
                            Name = "Sleek Metal Chair",
                            Price = 53m,
                            Status = 1,
                            Stock = 132
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2022, 3, 28, 1, 38, 6, 122, DateTimeKind.Unspecified).AddTicks(5678),
                            Name = "Ergonomic Concrete Soap",
                            Price = 49m,
                            Status = 1,
                            Stock = 141
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2021, 4, 25, 11, 5, 31, 845, DateTimeKind.Unspecified).AddTicks(7404),
                            Name = "Incredible Cotton Pizza",
                            Price = 52m,
                            Status = 1,
                            Stock = 197
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 12, 1, 0, 13, 12, 335, DateTimeKind.Unspecified).AddTicks(3963),
                            Name = "Incredible Concrete Towels",
                            Price = 50m,
                            Status = 1,
                            Stock = 14
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 1, 24, 14, 57, 26, 846, DateTimeKind.Unspecified).AddTicks(8444),
                            Name = "Sleek Cotton Sausages",
                            Price = 52m,
                            Status = 1,
                            Stock = 134
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 11, 13, 22, 10, 28, 59, DateTimeKind.Unspecified).AddTicks(2891),
                            Name = "Incredible Concrete Shoes",
                            Price = 55m,
                            Status = 1,
                            Stock = 122
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 10, 18, 19, 15, 13, 602, DateTimeKind.Unspecified).AddTicks(8848),
                            Name = "Practical Cotton Table",
                            Price = 51m,
                            Status = 1,
                            Stock = 174
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 2,
                            InsertedDate = new DateTime(2021, 7, 18, 6, 21, 52, 235, DateTimeKind.Unspecified).AddTicks(3351),
                            Name = "Small Cotton Pizza",
                            Price = 50m,
                            Status = 1,
                            Stock = 180
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 3, 4, 12, 52, 59, 975, DateTimeKind.Unspecified).AddTicks(3700),
                            Name = "Fantastic Rubber Pants",
                            Price = 52m,
                            Status = 1,
                            Stock = 109
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2021, 7, 18, 1, 33, 22, 275, DateTimeKind.Unspecified).AddTicks(3783),
                            Name = "Gorgeous Fresh Towels",
                            Price = 53m,
                            Status = 1,
                            Stock = 12
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 3, 20, 15, 30, 2, 222, DateTimeKind.Unspecified).AddTicks(7791),
                            Name = "Tasty Granite Car",
                            Price = 51m,
                            Status = 1,
                            Stock = 47
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2021, 9, 11, 8, 42, 38, 384, DateTimeKind.Unspecified).AddTicks(9622),
                            Name = "Gorgeous Metal Ball",
                            Price = 53m,
                            Status = 1,
                            Stock = 154
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 7,
                            InsertedDate = new DateTime(2022, 7, 7, 12, 47, 44, 532, DateTimeKind.Unspecified).AddTicks(5900),
                            Name = "Sleek Concrete Car",
                            Price = 49m,
                            Status = 1,
                            Stock = 8
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 5, 29, 4, 40, 8, 144, DateTimeKind.Unspecified).AddTicks(3812),
                            Name = "Intelligent Frozen Sausages",
                            Price = 54m,
                            Status = 1,
                            Stock = 106
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 10, 6, 18, 1, 58, 961, DateTimeKind.Unspecified).AddTicks(6905),
                            Name = "Handcrafted Wooden Fish",
                            Price = 51m,
                            Status = 1,
                            Stock = 40
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 8,
                            InsertedDate = new DateTime(2022, 12, 6, 13, 28, 50, 503, DateTimeKind.Unspecified).AddTicks(9611),
                            Name = "Awesome Plastic Hat",
                            Price = 56m,
                            Status = 1,
                            Stock = 138
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 10, 20, 13, 12, 4, 345, DateTimeKind.Unspecified).AddTicks(8560),
                            Name = "Handcrafted Rubber Mouse",
                            Price = 49m,
                            Status = 1,
                            Stock = 18
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 1,
                            InsertedDate = new DateTime(2021, 3, 28, 20, 47, 10, 726, DateTimeKind.Unspecified).AddTicks(1690),
                            Name = "Handmade Granite Mouse",
                            Price = 50m,
                            Status = 1,
                            Stock = 50
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 9, 27, 6, 41, 15, 528, DateTimeKind.Unspecified).AddTicks(8364),
                            Name = "Rustic Metal Mouse",
                            Price = 49m,
                            Status = 1,
                            Stock = 133
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 4,
                            InsertedDate = new DateTime(2021, 3, 27, 19, 13, 52, 469, DateTimeKind.Unspecified).AddTicks(6310),
                            Name = "Sleek Metal Ball",
                            Price = 54m,
                            Status = 1,
                            Stock = 132
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 9, 19, 3, 57, 4, 642, DateTimeKind.Unspecified).AddTicks(2694),
                            Name = "Fantastic Cotton Fish",
                            Price = 49m,
                            Status = 1,
                            Stock = 59
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 10,
                            InsertedDate = new DateTime(2022, 5, 1, 12, 44, 40, 828, DateTimeKind.Unspecified).AddTicks(2822),
                            Name = "Small Metal Bike",
                            Price = 57m,
                            Status = 1,
                            Stock = 10
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 10, 20, 23, 21, 39, 556, DateTimeKind.Unspecified).AddTicks(7050),
                            Name = "Handmade Soft Soap",
                            Price = 56m,
                            Status = 1,
                            Stock = 87
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2021, 9, 22, 10, 5, 17, 766, DateTimeKind.Unspecified).AddTicks(9440),
                            Name = "Licensed Rubber Salad",
                            Price = 49m,
                            Status = 1,
                            Stock = 73
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2022, 3, 15, 21, 13, 52, 906, DateTimeKind.Unspecified).AddTicks(3359),
                            Name = "Rustic Steel Gloves",
                            Price = 52m,
                            Status = 1,
                            Stock = 146
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 6,
                            InsertedDate = new DateTime(2022, 9, 13, 7, 43, 51, 49, DateTimeKind.Unspecified).AddTicks(9431),
                            Name = "Licensed Plastic Pants",
                            Price = 55m,
                            Status = 1,
                            Stock = 139
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 9,
                            InsertedDate = new DateTime(2021, 3, 30, 18, 13, 15, 537, DateTimeKind.Unspecified).AddTicks(4146),
                            Name = "Awesome Rubber Shoes",
                            Price = 52m,
                            Status = 1,
                            Stock = 197
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 3,
                            InsertedDate = new DateTime(2021, 8, 9, 8, 50, 31, 424, DateTimeKind.Unspecified).AddTicks(707),
                            Name = "Incredible Metal Soap",
                            Price = 55m,
                            Status = 1,
                            Stock = 163
                        });
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Product", b =>
                {
                    b.HasOne("TrueOnion.DOMAIN.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrueOnion.DOMAIN.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
